In [5]:
import pandas as pd

In [6]:
df = pd.read_csv(r"C:\Users\anfre\Downloads\Listado-de-proveedores-y-contactos.csv",encoding="latin-1",sep=";")

df

,ID,Proveedor,Contacto comercial,Email,Teléfono,Saldo pendiente,Fecha de última compra,Unnamed: 7
0,P0001,So Factive,Lorenzo Cantón Galan,fluffy@verizon.net,(394) 406-8708,63,4/09/2018,NaN
1,P0002,Kontroller,Adelina Valls Canet,fraterk@me.com,(923) 207-3871,4250,8/06/2012,NaN
2,P0003,Finance Api,Eulalia del Galindo,animats@mac.com,(904) 363-2261,2412,6/08/2017,NaN
3,P0004,Biomotivate,Tania Catalán Galván,tbeck@icloud.com,(923) 671-4117,3348,22/05/2017,NaN
4,P0005,Deltavita,Abraham Girón-Soler,mallanmba@yahoo.ca,(841) 798-8943,570,17/01/2022,NaN
...,...,...,...,...,...,...,...,...
994,P0995,Actenet,Gabriel Arnau,telbij@yahoo.com,(456) 843-7004,7876,19/07/2017,NaN
995,P0996,Datawrite,Gala Millán Ribera,payned@mac.com,(655) 690-1559,4703,22/05/2012,NaN
996,P0997,Echo Digital,Luis Ángel Llanos Benavente,chrwin@live.com,(444) 586-0540,2786,1/06/2021,NaN
997,P0998,Meussicz,Tere Monreal Botella,stellaau@me.com,(752) 359-9358,3442,28/06/2016,NaN
998,P0999,Learnig,Pepito Catalá-Niño,elmer@verizon.net,(716) 835-7132,2505,20/02/2021,NaN

In [7]:
## Se elimina la columna Unnamed 7
df = df.drop('Unnamed: 7', axis=1)

In [8]:
df

,ID,Proveedor,Contacto comercial,Email,Teléfono,Saldo pendiente,Fecha de última compra
0,P0001,So Factive,Lorenzo Cantón Galan,fluffy@verizon.net,(394) 406-8708,63,4/09/2018
1,P0002,Kontroller,Adelina Valls Canet,fraterk@me.com,(923) 207-3871,4250,8/06/2012
2,P0003,Finance Api,Eulalia del Galindo,animats@mac.com,(904) 363-2261,2412,6/08/2017
3,P0004,Biomotivate,Tania Catalán Galván,tbeck@icloud.com,(923) 671-4117,3348,22/05/2017
4,P0005,Deltavita,Abraham Girón-Soler,mallanmba@yahoo.ca,(841) 798-8943,570,17/01/2022
...,...,...,...,...,...,...,...
994,P0995,Actenet,Gabriel Arnau,telbij@yahoo.com,(456) 843-7004,7876,19/07/2017
995,P0996,Datawrite,Gala Millán Ribera,payned@mac.com,(655) 690-1559,4703,22/05/2012
996,P0997,Echo Digital,Luis Ángel Llanos Benavente,chrwin@live.com,(444) 586-0540,2786,1/06/2021
997,P0998,Meussicz,Tere Monreal Botella,stellaau@me.com,(752) 359-9358,3442,28/06/2016
998,P0999,Learnig,Pepito Catalá-Niño,elmer@verizon.net,(716) 835-7132,2505,20/02/2021

In [9]:
## ¿Cuál es el proveedor al que se le realizó el pedido de mayor valor?

saldo_maximo = df['Saldo pendiente'].max()
print(saldo_maximo)

18254

In [10]:
fila_saldo_maximo = df.loc[df['Saldo pendiente'].idxmax()]
print(fila_saldo_maximo)

ID                                               P0008
Proveedor                                       Player
Contacto comercial        Valentina Enríquez Montalbán
Email                                    lukka@mac.com
Teléfono                                (953) 242-4312
Saldo pendiente                                  18254
Fecha de última compra                       6/01/2019
Name: 7, dtype: object

In [ ]:
# ¿Cuales son los provedores con un saldo superior a 8000?
proveedores_alta_deuda = df[df['Saldo pendiente'] > 8000]

# Mostrar el resultado
print(proveedores_alta_deuda)

        ID                Proveedor                  Contacto comercial  \
7    P0008                   Player        Valentina Enríquez Montalbán
13   P0014                   Bayesa               Heliodoro Baños Sainz
20   P0021                 2gm Fuji   Inmaculada Aurora Cantero Peralta
28   P0029                    Myrgy                  Maximino del Prada
34   P0035         Caron Management               Macaria de Santamaría
56   P0057           Walna Dynamics                     Jesús Abad Lago
74   P0075                   Toytha               Malena Olivera Ropero
90   P0091           Ives Ives Ives                 Maite Vargas Roldan
97   P0098                  Nestens               Chelo Acedo-Corominas
123  P0124             City Of Lyon  Juan Bautista Jesús Gibert Alcázar
132  P0133                Fercussir            Epifanio Roldán Bautista
134  P0135                    Orron                    Juliana del Cano
141  P0142       Superhome Fashions                   Benito Pi Pedraza
145  P0146     Modern Clothesopolis              Eliseo Ródenas Llabrés
177  P0178                  Joyance                Heraclio Franco Vila
185  P0186          Digital Tactics              Ruth Cifuentes Sevilla
207  P0208          Impact d'équipe             Macaria Benito Armengol
209  P0210         Recherche de pub               Julián Méndez Barroso
212  P0213       Solutions Zénitcom            Patricia Pinilla-Esparza
217  P0218                   Myrgie                 Julie Niño Pellicer
223  P0224                Usine 2cv                  Régulo Plaza Jerez
224  P0225         Nouvelle culture                  Laura Jaén Álvarez
256  P0257                 Carrière               Mauricio Cuervo Lluch
286  P0287       A secoué 4 enfants    Gisela Berta Benítez Ballesteros
301  P0302           Semble Meubles                     Calixto Borrego
329  P0330                Wappifier                   Mayte Bou Cabezas
344  P0345                  Spieler                Sancho Llabrés Gallo
359  P0360        Optimierungslogik              Pepita Vendrell Rosado
365  P0366          Der Rotary-Club                Débora Arroyo Pastor
372  P0373           Csw-Ressourcen               Édgar Bautista Hervia
382  P0383            Insel Impacex                        Hernán Duque
389  P0390              Blaugebohrt                    Dionisia Peinado
394  P0395             Visionssport                  Lupe Guerra-Huguet
396  P0397                  Neue VR                   Dionisia de Amaya
403  P0404                Allgemein                       Lucila Losada
522  P0523       Autopeças Maverick                  Eusebia Sola Ayala
536  P0537       Mudança de opinião                      Milagros Casas
537  P0538                   Núcleo          Ramona Dora Marcos Maestre
550  P0551        Solução principal                 Chuy Briones Martín
558  P0559        Abalou 4 crianças                          Valero Rey
637  P0638           Dinàmica Walna                   Julián Ruiz-Badía
647  P0648     Ciutat de Revelstoke            Adalberto Ortiz Meléndez
655  P0656               Iti Tècnic                    Calixta Pallarès
668  P0669           Solució bàsica              Atilio Sala Echevarría
680  P0681             Roba Moderna          Calixta Fábregas Caballero
693  P0694        El Servei Home It                Antonio Pardo-Bilbao
710  P0711          Dissenys Adview             Violeta Buendía Bárcena
729  P0730              Fuji da 2 g               Roldán Aparicio Recio
741  P0742          Foresta ventosa               Teodoro Osorio Carpio
743  P0744       Trasporto in linea                Graciana Pintor Alba
818  P0819         Arredamento Cafè                 Sancho Melero Palma
829  P0830                    Zolfo                 Nilda Ruano Calleja
836  P0837  Grande spazio di backup                  Magdalena Morcillo
849  P0850                    Cat51              Graciana Juan Llorente
857  P0858        Creative Solution              Pascuala Linares Manso
860  P0861              Infineramic               Etelvina Clavero Malo
886  P0887          Alegra Dynamics                 Roberta Cobos Baeza
929  P0930           Impalafabbrica                  Rafaela de Collado
971  P0972           Bk Fechtverein                     Vito Mesa-Ayala
984  P0985             Hyperlokalis              Rómulo Herranz-Gallart

                       Email        Teléfono  Saldo pendiente  \
7              lukka@mac.com  (953) 242-4312            18254
13        zavadsky@gmail.com  (495) 936-2371             8121
20          sacraver@aol.com  (618) 384-8498             8231
28       dunstan@verizon.net  (458) 694-0732             8065
34           mavilar@msn.com  (969) 346-7723             8474
56     chaikin@optonline.net  (465) 470-3259             8455
74             boein@msn.com  (415) 786-5209             8151
90       erynf@sbcglobal.net  (814) 244-3554             8367
97          heroine@live.com  (394) 225-8488             8172
123      drolsky@hotmail.com  (205) 367-3867             8430
132          firstpr@att.net  (504) 730-3023             8346
134      andersbr@icloud.com  (287) 956-0147             8037
141           simone@att.net  (794) 588-1941             8184
145    jimmichie@hotmail.com  (713) 545-9434             8386
177            jorgb@aol.com  (752) 738-1233             8370
185       farber@comcast.net  (688) 516-3513             8172
207           ebassi@msn.com  (290) 976-0868             8380
209         scottzed@aol.com  (264) 298-6094             8113
212         sfoskett@aol.com  (566) 798-8666             8420
217        boftx@outlook.com  (260) 827-6778             8203
223        salesgeek@mac.com  (876) 215-3650             8023
224        jgmyers@yahoo.com  (991) 989-8445             8167
256    catalog@optonline.net  (757) 447-7689             8437
286         wildfire@msn.com  (870) 412-0760             8146
301    tsuruta@optonline.net  (889) 796-0357             8217
329    duncand@optonline.net  (908) 507-7774             8110
344         ribet@icloud.com  (268) 963-1280             8114
359          bester@live.com  (259) 824-1957             8056
365      barnett@comcast.net  (248) 338-4237             8017
372       isotopian@yahoo.ca  (480) 956-2597             8066
382            munge@mac.com  (477) 246-0094             8155
389           graham@att.net  (917) 389-5749             8119
394          thomasj@att.net  (741) 322-3722             8465
396       wainwrig@yahoo.com  (652) 909-5556             8227
403      smpeters@icloud.com  (776) 768-7137             8495
522         mkearl@gmail.com  (463) 662-6107             8402
536          bastian@att.net  (741) 803-0434             8452
537             retoh@me.com  (293) 469-1962             8016
550      kjetilk@comcast.net  (351) 615-4357             8486
558      rcwil@optonline.net  (455) 474-0513             8224
637       jfinke@verizon.net  (913) 528-2635             8243
647        fukuchi@yahoo.com  (775) 733-8457             8472
655       jamuir@hotmail.com  (990) 448-2648             8365
668     rsteiner@outlook.com  (203) 926-5564             8219
680        mcmillan@yahoo.ca  (666) 419-9076             8412
693   burniske@sbcglobal.net  (959) 319-5027             8430
710       djupedal@gmail.com  (697) 851-5459             8137
729      wortmanj@icloud.com  (759) 523-1918             8222
741        hllam@outlook.com  (685) 627-4277             8280
743           munson@mac.com  (397) 447-9975             8147
818     jnolan@optonline.net  (724) 320-3828             8260
829        bmidd@hotmail.com  (791) 605-2725             8260
836      jlbaumga@icloud.com  (311) 232-8817             8482
849      pemungkah@gmail.com  (263) 756-4415             8439
857          mhassel@att.net  (488) 569-4836             8423
860  bigmauler@optonline.net  (723) 467-3052             8397
886           dpitts@msn.com  (666) 532-5881             8473
929           nacho@yahoo.ca  (692) 768-7903             8118
971          catalog@mac.com  (917) 921-0105             8359
984           munge@yahoo.ca  (853) 740-8378             8394

    Fecha de última compra
7                6/01/2019
13              13/03/2015
20              22/07/2012
28              17/03/2016
34              27/09/2019
56               9/03/2020
74              27/12/2016
90              27/08/2021
97               1/09/2012
123             15/05/2015
132             24/06/2016
134             13/01/2018
141             23/06/2017
145             12/04/2019
177             30/04/2016
185             22/01/2018
207             27/02/2021
209             16/04/2017
212             23/03/2017
217              5/04/2022
223             12/06/2015
224             17/10/2016
256             24/04/2013
286              2/07/2012
301             25/03/2021
329              5/03/2019
344             19/10/2021
359              1/02/2020
365             25/12/2012
372             29/08/2021
382             24/04/2022
389             14/05/2012
394             18/03/2019
396             14/08/2014
403             23/09/2012
522             17/05/2018
536             23/06/2012
537              5/09/2019
550             27/05/2012
558             14/05/2012
637             30/11/2013
647             10/09/2016
655             28/04/2017
668              9/03/2019
680              2/11/2020
693             14/11/2019
710              1/10/2015
729             12/10/2021
741              6/05/2012
743             12/04/2016
818              4/09/2013
829              2/08/2019
836              6/04/2018
849             16/04/2012
857             10/04/2020
860              2/04/2019
886              2/09/2017
929             22/11/2019
971             23/12/2014
984              7/10/2018

In [17]:
resultado_limpio = df.loc[df['Saldo pendiente'] > 8000, ['Proveedor', 'Saldo pendiente']]

# Mostrar el resultado
print(resultado_limpio)

                   Proveedor  Saldo pendiente
7                     Player            18254
13                    Bayesa             8121
20                  2gm Fuji             8231
28                     Myrgy             8065
34          Caron Management             8474
56            Walna Dynamics             8455
74                    Toytha             8151
90            Ives Ives Ives             8367
97                   Nestens             8172
123             City Of Lyon             8430
132                Fercussir             8346
134                    Orron             8037
141       Superhome Fashions             8184
145     Modern Clothesopolis             8386
177                  Joyance             8370
185          Digital Tactics             8172
207          Impact d'équipe             8380
209         Recherche de pub             8113
212       Solutions Zénitcom             8420
217                   Myrgie             8203
223                Usine 2cv             8023
224         Nouvelle culture             8167
256                 Carrière             8437
286       A secoué 4 enfants             8146
301           Semble Meubles             8217
329                Wappifier             8110
344                  Spieler             8114
359        Optimierungslogik             8056
365          Der Rotary-Club             8017
372           Csw-Ressourcen             8066
382            Insel Impacex             8155
389              Blaugebohrt             8119
394             Visionssport             8465
396                  Neue VR             8227
403                Allgemein             8495
522       Autopeças Maverick             8402
536       Mudança de opinião             8452
537                   Núcleo             8016
550        Solução principal             8486
558        Abalou 4 crianças             8224
637           Dinàmica Walna             8243
647     Ciutat de Revelstoke             8472
655               Iti Tècnic             8365
668           Solució bàsica             8219
680             Roba Moderna             8412
693        El Servei Home It             8430
710          Dissenys Adview             8137
729              Fuji da 2 g             8222
741          Foresta ventosa             8280
743       Trasporto in linea             8147
818         Arredamento Cafè             8260
829                    Zolfo             8260
836  Grande spazio di backup             8482
849                    Cat51             8439
857        Creative Solution             8423
860              Infineramic             8397
886          Alegra Dynamics             8473
929           Impalafabbrica             8118
971           Bk Fechtverein             8359
984             Hyperlokalis             8394

In [18]:
## ¿Cuál ha sido el valor total gastado en proveedores durante cada año?

# 2. Convertir 'Fecha de última compra' a tipo datetime
# Indicamos dayfirst=True ya que tus fechas están en formato día/mes/año (ej. 4/09/2018)
df['Fecha de última compra'] = pd.to_datetime(df['Fecha de última compra'], dayfirst=True)

# 3. Crear una nueva columna solo con el año
df['Año'] = df['Fecha de última compra'].dt.year

# 4. Agrupar por el año y calcular la suma del saldo
gasto_por_año = df.groupby('Año')['Saldo pendiente'].sum().reset_index()

# 5. Cambiar el nombre de las columnas para que sea más claro y mostrar el resultado
gasto_por_año.columns = ['Año', 'Total Gastado']
print(gasto_por_año)

     Año  Total Gastado
0   2011          14204
1   2012         536022
2   2013         357810
3   2014         240545
4   2015         330082
5   2016         438315
6   2017         476377
7   2018         427567
8   2019         421750
9   2020         423850
10  2021         457062
11  2022         142393