In [ ]:
## PRIMERO IMPORTAR LA LIBRERIA REQUESTS, LUEGO INICIO LA CONEXION CON LA API ##

In [21]:
import requests
base_url = "https://api-colombia.com/"
endpoint = "/api/v1/Airport"
requests.get(base_url + endpoint)

In [ ]:
## AL OBTENER UN RESPUESTA DE CODIGO 200 SE ENTIENDE QUE LA CONEXION ES EXITOSA ##

In [22]:
respuesta_api = requests.get(base_url + endpoint)

In [ ]:
## AHORA EXTRAIGO LA INFORMACION DE LA API ##

In [23]:
respuesta_api.json()

[{'id': 45,
  'name': 'Base Aérea BG. Arturo Lema Posada',
  'iataCode': 'N/A',
  'oaciCode': 'N/A',
  'type': 'Militar',
  'deparmentId': 2,
  'department': {'id': 2,
   'name': 'Antioquia',
   'description': 'Antioquia es uno de los treinta y dos departamentos que, junto con Bogotá, Distrito Capital, forman la República de Colombia. Su capital es Medellín, la segunda ciudad más poblada del país. Está ubicado al noroccidente colombiano, en las regiones Andina y Caribe, limitando al norte con el mar Caribe (océano Atlántico), Córdoba y Bolívar, al este con Santander y Boyacá, al sur con Caldas y Risaralda, y al oeste con Chocó. Con unos 6 500 000 habitantes en 2015 es el departamento más poblado, y con 63 600 km², el sexto más extenso, superado por Amazonas, Vichada, Caquetá, Meta y Guainía.',
   'cityCapitalId': 12,
   'municipalities': 125,
   'surface': 63612,
   'population': 6887306,
   'phonePrefix': '4',
   'countryId': 1,
   'cityCapital': None,
   'country': None,
   'cities': None,
   'regionId': 5,
   'region': None,
   'naturalAreas': None,
   'maps': None,
   'indigenousReservations': None,
   'airports': [None]},
  'cityId': 91,
  'city': {'id': 91,
   'name': 'Rionegro',
   'description': 'Rionegro es un municipio de Colombia, ubicado en el departamento de Antioquia. Está localizado en el valle de San Nicolás o también llamado Altiplano del Oriente, en la subregión Oriente, siendo la ciudad con mayor población y la que concentra el movimiento económico de la subregión. Está ubicada a tan solo 35 minutos de Medellín, capital del departamento, gracias al túnel de interconexión Aburrá-Oriente. Su nombre oficial es Ciudad Santiago de Arma de Rionegro.',
   'surface': 196,
   'population': 135465,
   'postalCode': '54040',
   'departmentId': 2,
   'department': None,
   'touristAttractions': None,
   'presidents': None,
   'indigenousReservations': None,
   'airports': [None],
   'radios': None,
   'urbanCenters': None,
   'higherEducationInstitutions': None,
   'televisionChannels': None},
  'latitude': -75.42037792,
  'longitude': 6.166336066},
 {'id': 9,
  'name': 'Aeropuerto Internacional José María Córdova',
  'iataCode': 'MDE',
  'oaciCode': 'SKRG',
  'type': 'Internacional',
  'deparmentId': 2,
  'department': {'id': 2,
   'name': 'Antioquia',
   'description': 'Antioquia es uno de los treinta y dos departamentos que, junto con Bogotá, Distrito Capital, forman la República de Colombia. Su capital es Medellín, la segunda ciudad más poblada del país. Está ubicado al noroccidente colombiano, en las regiones Andina y Caribe, limitando al norte con el mar Caribe (océano Atlántico), Córdoba y Bolívar, al este con Santander y Boyacá, al sur con Caldas y Risaralda, y al oeste con Chocó. Con unos 6 500 000 habitantes en 2015 es el departamento más poblado, y con 63 600 km², el sexto más extenso, superado por Amazonas, Vichada, Caquetá, Meta y Guainía.',
   'cityCapitalId': 12,
   'municipalities': 125,
   'surface': 63612,
   'population': 6887306,
   'phonePrefix': '4',
   'countryId': 1,
   'cityCapital': None,
   'country': None,
   'cities': None,
   'regionId': 5,
   'region': None,
   'naturalAreas': None,
   'maps': None,
   'indigenousReservations': None,
   'airports': [None]},
  'cityId': 91,
  'city': {'id': 91,
   'name': 'Rionegro',
   'description': 'Rionegro es un municipio de Colombia, ubicado en el departamento de Antioquia. Está localizado en el valle de San Nicolás o también llamado Altiplano del Oriente, en la subregión Oriente, siendo la ciudad con mayor población y la que concentra el movimiento económico de la subregión. Está ubicada a tan solo 35 minutos de Medellín, capital del departamento, gracias al túnel de interconexión Aburrá-Oriente. Su nombre oficial es Ciudad Santiago de Arma de Rionegro.',
   'surface': 196,
   'population': 135465,
   'postalCode': '54040',
   'departmentId': 2,
   'department': None,
   'touristAttractions': None,
   'presidents': None,
   'indigenousReservations': None,
   'airports': [None],
   'radios': None,
   'urbanCenters': None,
   'higherEducationInstitutions': None,
   'televisionChannels': None},
  'latitude': -75.423110000511,
  'longitude': 6.1645330006573},
 {'id': 35,
  'name': 'Aeropuerto Los Colonizadores',
  'iataCode': 'RVE',
  'oaciCode': 'SKSA',
  'type': 'Nacional',
  'deparmentId': 3,
  'department': {'id': 3,
   'name': 'Arauca',
   'description': 'Arauca es uno de los treinta y dos departamentos que, junto con Bogotá, Distrito Capital, forman la República de Colombia. Su capital es la homónima Arauca. Está ubicado al este del país, en la región Orinoquía, limitando al norte y este con Venezuela, al sur con Vichada y Casanare, y al oeste con Boyacá',
   'cityCapitalId': 143,
   'municipalities': 7,
   'surface': 23818,
   'population': 304978,
   'phonePrefix': '7',
   'countryId': 1,
   'cityCapital': None,
   'country': None,
   'cities': None,
   'regionId': 3,
   'region': None,
   'naturalAreas': None,
   'maps': None,
   'indigenousReservations': None,
   'airports': [None]},
  'cityId': 141,
  'city': {'id': 141,
   'name': 'Saravena',
   'description': '',
   'surface': None,
   'population': None,
   'postalCode': None,
   'departmentId': 3,
   'department': None,
   'touristAttractions': None,
   'presidents': None,
   'indigenousReservations': None,
   'airports': [None],
   'radios': None,
   'urbanCenters': None,
   'higherEducationInstitutions': None,
   'televisionChannels': None},
  'latitude': -71.8605600056216,
  'longitude': 6.9566401818432},
 {'id': 41,
  'name': 'Aeropuerto Gabriel Vargas Santos',
  'iataCode': 'TME',
  'oaciCode': 'SKTM',
  'type': 'Nacional',
  'deparmentId': 3,
  'department': {'id': 3,
   'name': 'Arauca',
   'description': 'Arauca es uno de los treinta y dos departamentos que, junto con Bogotá, Distrito Capital, forman la República de Colombia. Su capital es la homónima Arauca. Está ubicado al este del país, en la región Orinoquía, limitando al norte y este con Venezuela, al sur con Vichada y Casanare, y al oeste con Boyacá',
   'cityCapitalId': 143,
   'municipalities': 7,
   'surface': 23818,
   'population': 304978,
   'phonePrefix': '7',
   'countryId': 1,
   'cityCapital': None,
   'country': None,
   'cities': None,
   'regionId': 3,
   'region': None,
   'naturalAreas': None,
   'maps': None,
   'indigenousReservations': None,
   'airports': [None]},
  'cityId': 142,
  'city': {'id': 142,
   'name': 'Tame',
   'description': '',
   'surface': None,
   'population': None,
   'postalCode': None,
   'departmentId': 3,
   'department': None,
   'touristAttractions': None,
   'presidents': None,
   'indigenousReservations': None,
   'airports': [None],
   'radios': None,
   'urbanCenters': None,
   'higherEducationInstitutions': None,
   'televisionChannels': None},
  'latitude': -71.7602985282201,
  'longitude': 6.4499321697396},
 {'id': 16,
  'name': 'Aeropuerto Santiago Pérez Quiroz',
  'iataCode': 'AUC',
  'oaciCode': 'SKUC',
  'type': 'Nacional',
  'deparmentId': 3,
  'department': {'id': 3,
   'name': 'Arauca',
   'description': 'Arauca es uno de los treinta y dos departamentos que, junto con Bogotá, Distrito Capital, forman la República de Colombia. Su capital es la homónima Arauca. Está ubicado al este del país, en la región Orinoquía, limitando al norte y este con Venezuela, al sur con Vichada y Casanare, y al oeste con Boyacá',
   'cityCapitalId': 143,
   'municipalities': 7,
   'surface': 23818,
   'population': 304978,
   'phonePrefix': '7',
   'countryId': 1,
   'cityCapital': None,
   'country': None,
   'cities': None,
   'regionId': 3,
   'region': None,
   'naturalAreas': None,
   'maps': None,
   'indigenousReservations': None,
   'airports': [None]},
  'cityId': 143,
  'city': {'id': 143,
   'name': 'Arauca',
   'description': 'Arauca, cuyo nombre colonial es Villa de Santa Bárbara de Arauca, es un municipio colombiano, capital del departamento de Arauca. Está localizado sobre el margen sur del río Arauca. Limita con Venezuela al norte, con la cual está conectada mediante el Puente Internacional José Antonio Páez y se comunica por vía terrestre hacia el centro de Colombia mediante la Ruta de los Libertadores',
   'surface': 5841,
   'population': 96814,
   'postalCode': '810001',
   'departmentId': 3,
   'department': None,
   'touristAttractions': None,
   'presidents': None,
   'indigenousReservations': None,
   'airports': [None],
   'radios': None,
   'urbanCenters': None,
   'higherEducationInstitutions': None,
   'televisionChannels': None},
  'latitude': -70.7369359999433,
  'longitude': 7.0689110004557},
 {'id': 2,
  'name': 'Aeropuerto Internacional Ernesto Cortissoz',
  'iataCode': 'BAQ',
  'oaciCode': 'SKBQ',
  'type': 'Internacional',
  'deparmentId': 4,
  'department': {'id': 4,
   'name': 'Atlántico',
   'description': 'El Atlántico es uno de los treinta y dos departamentos que, junto a Bogotá, Distrito Capital, forman la República de Colombia. Su capital es Barranquilla. Ubicado en la región Caribe, limita al norte con el mar Caribe, al Oriente con el río Magdalena y al Sur y al Occidente con el departamento de Bolívar. Con unos 2 500 000 habitantes en 2015, es el cuarto departamento más poblado (por detrás de Antioquia, Valle del Cauca y Cundinamarca); con 3019 km² es el tercero menos extenso (por delante de Quindío y San Andrés y Providencia, el menos extenso) y con 815 hab/km² es el segundo más densamente poblado (por detrás de San Andrés y Providencia)',
   'cityCapitalId': 144,
   'municipalities': 23,
   'surface': 3388,
   'population': 2804025,
   'phonePrefix': '5',
   'countryId': 1,
   'cityCapital': None,
   'country': None,
   'cities': None,
   'regionId': 1,
   'region': None,
   'naturalAreas': None,
   'maps': None,
   'indigenousReservations': None,
   'airports': [None]},
  'cityId': 144,
  'city': {'id': 144,
   'name': 'Barranquilla',
   'description': 'El Área metropolitana de Barranquilla es una conurbación colombiana ubicada en el norte del departamento de Atlántico. Su municipio principal es la capital departamental Barranquilla, y los otros municipios periféricos que la integran son Soledad, Galapa, Puerto Colombia y Malambo. Es la primera conurbación de la Región Caribe, la más densamente poblada y la cuarta del país.',
   'surface': 520,
   'population': 2326292,
   'postalCode': '80001',
   'departmentId': 4,
   'department': None,
   'touristAttractions': None,
   'presidents': None,
   'indigenousReservations': None,
   'airports': [None],
   'radios': None,
   'urbanCenters': None,
   'higherEducationInstitutions': None,
   'televisionChannels': None},
  'latitude': -74.7806769994191,
  'longitude': 10.8894609990694},
 {'id': 7,
  'name': 'Aeropuerto Internacional Rafael Núñez',
  'iataCode': 'CTG',
  'oaciCode': 'SKCG',
  'type': 'Internacional',
  'deparmentId': 6,
  'department': {'id': 6,
   'name': 'Bolívar',
   'description': 'Bolívar es uno de los treinta y dos departamentos que, junto con Bogotá, Distrito Capital, forman la República de Colombia. Su capital es Cartagena de Indias, sede de la asamblea departamental, mientras que en Turbaco se encuentra la sede de la gobernación. Está ubicado en la región Caribe, limitando al norte con el mar Caribe (océano Atlántico), al noreste con Atlántico, al este con Magdalena y Cesar, al sureste con Santander, al suroeste con Antioquia y al oeste con Córdoba y Sucre.',
   'cityCapitalId': 210,
   'municipalities': 45,
   'surface': 25978,
   'population': 2236603,
   'phonePrefix': '5',
   'countryId': 1,
   'cityCapital': None,
   'country': None,
   'cities': None,
   'regionId': 1,
   'region': None,
   'naturalAreas': None,
   'maps': None,
   'indigenousReservations': None,
   'airports': [None]},
  'cityId': 203,
  'city': {'id': 203,
   'name': 'El Carmen de Bolívar',
   'description': 'El Carmen de Bolívar es un municipio del departamento de Bolívar, Colombia, ubicado en el sistema orográfico de los Montes de María, siendo la población más grande, así como la que concentra el movimiento económico y comercial de la subregión. Está a 120 km al sudeste de Cartagena de Indias y a 69 km al norte de Sincelejo.',
   'surface': 954,
   'population': 70131,
   'postalCode': '132050',
   'departmentId': 6,
   'department': None,
   'touristAttractions': None,
   'presidents': None,
   'indigenousReservations': None,
   'airports': [None],
   'radios': None,
   'urbanCenters': None,
   'higherEducationInstitutions': None,
   'televisionChannels': None},
  'latitude': -75.5153339592878,
  'longitude': 10.4449415954788},
 {'id': 43,
  'name': 'Aeropuerto del Café',
  'iataCode': 'N/A',
  'oaciCode': 'N/A',
  'type': 'En Construccion',
  'deparmentId': 8,
  'department': {'id': 8,
   'name': 'Caldas',
   'description': 'Caldas es uno de los treinta y dos departamentos que, junto con Bogotá, Distrito Capital, forman la República de Colombia. Su capital es Manizales. Está ubicado en el centro del país, en la región andina, limitando al norte con Antioquia, al noreste con Boyacá, al este con Cundinamarca, al sur con Tolima y Risaralda y al oeste con Risaralda. Con 7888\xa0km² es el quinto departamento menos extenso —por delante de Risaralda, Atlántico, Quindío y San Andrés y Providencia, el menos extenso— y con 125 hab/km², el sexto más densamente poblado, por detrás de San Andrés y Providencia, Atlántico, Quindío, Risaralda y Valle del Cauca',
   'cityCapitalId': 337,
   'municipalities': 27,
   'surface': 7888,
   'population': 1036455,
   'phonePrefix': '6',
   'countryId': 1,
   'cityCapital': None,
   'country': None,
   'cities': None,
   'regionId': 5,
   'region': None,
   'naturalAreas': None,
   'maps': None,
   'indigenousReservations': None,
   'airports': [None]},
  'cityId': 337,
  'city': {'id': 337,
   'name': 'Manizales',
   'description': 'Manizales es un municipio colombiano, capital del departamento de Caldas. Está ubicado en el centro occidente de Colombia en la región paisa, así como en el eje cafetero, sobre la Cordillera Central de los Andes, cerca del Nevado del Ruiz. Tiene una población de 454,077 habitantes (2022). Es la región más poblada y competitiva del departamento con un aporte del 68% de su PIB total.',
   'surface': 571,
   'population': 454077,
   'postalCode': '170001',
   'departmentId': 8,
   'department': None,
   'touristAttractions': None,
   'presidents': None,
   'indigenousReservations': None,
   'airports': [None],
   'radios': None,
   'urbanCenters': None,
   'higherEducationInstitutions': None,
   'televisionChannels': None},
  'latitude': 0,
  'longitude': 0},
 {'id': 24,
  'name': 'Aeropuerto La Nubia',
  'iataCode': 'MZL',
  'oaciCode': 'SKMZ',
  'type': 'Nacional',
  'deparmentId': 8,
  'department': {'id': 8,
   'name': 'Caldas',
   'description': 'Caldas es uno de los treinta y dos departamentos que, junto con Bogotá, Distrito Capital, forman la República de Colombia. Su capital es Manizales. Está ubicado en el centro del país, en la región andina, limitando al norte con Antioquia, al noreste con Boyacá, al este con Cundinamarca, al sur con Tolima y Risaralda y al oeste con Risaralda. Con 7888\xa0km² es el quinto departamento menos extenso —por delante de Risaralda, Atlántico, Quindío y San Andrés y Providencia, el menos extenso— y con 125 hab/km², el sexto más densamente poblado, por detrás de San Andrés y Providencia, Atlántico, Quindío, Risaralda y Valle del Cauca',
   'cityCapitalId': 337,
   'municipalities': 27,
   'surface': 7888,
   'population': 1036455,
   'phonePrefix': '6',
   'countryId': 1,
   'cityCapital': None,
   'country': None,
   'cities': None,
   'regionId': 5,
   'region': None,
   'naturalAreas': None,
   'maps': None,
   'indigenousReservations': None,
   'airports': [None]},
  'cityId': 337,
  'city': {'id': 337,
   'name': 'Manizales',
   'description': 'Manizales es un municipio colombiano, capital del departamento de Caldas. Está ubicado en el centro occidente de Colombia en la región paisa, así como en el eje cafetero, sobre la Cordillera Central de los Andes, cerca del Nevado del Ruiz. Tiene una población de 454,077 habitantes (2022). Es la región más poblada y competitiva del departamento con un aporte del 68% de su PIB total.',
   'surface': 571,
   'population': 454077,
   'postalCode': '170001',
   'departmentId': 8,
   'department': None,
   'touristAttractions': None,
   'presidents': None,
   'indigenousReservations': None,
   'airports': [None],
   'radios': None,
   'urbanCenters': None,
   'higherEducationInstitutions': None,
   'televisionChannels': None},
  'latitude': -75.4692103507527,
  'longitude': 5.0293625217822},
 {'id': 51,
  'name': 'Base Aérea de Tres Esquinas',
  'iataCode': 'TQS',
  'oaciCode': 'SKTQ',
  'type': 'Militar',
  'deparmentId': 9,
  'department': {'id': 9,
   'name': 'Caquetá',
   'description': 'Caquetá es uno de los treinta y dos departamentos que, junto con Bogotá, Distrito Capital, forman la República de Colombia. Su capital es Florencia. Está ubicado al sur del país, en la región Amazonia, limitando al norte con Meta y Guaviare, al noreste con Vaupés, al sur con Amazonas y Putumayo, y al oeste con Cauca y Huila. Con 88 965 km² es el tercer departamento más extenso —por detrás de Amazonas y Vichada—. Todos sus municipios forman parte de los territorios focalizados',
   'cityCapitalId': 364,
   'municipalities': 16,
   'surface': 88965,
   'population': 419275,
   'phonePrefix': '8',
   'countryId': 1,
   'cityCapital': None,
   'country': None,
   'cities': None,
   'regionId': 4,
   'region': None,
   'naturalAreas': None,
   'maps': None,
   'indigenousReservations': None,
   'airports': [None]},
  'cityId': 371,
  'city': {'id': 371,
   'name': 'Solano',
   'description': '',
   'surface': None,
   'population': None,
   'postalCode': None,
   'departmentId': 9,
   'department': None,
   'touristAttractions': None,
   'presidents': None,
   'indigenousReservations': None,
   'airports': [None],
   'radios': None,
   'urbanCenters': None,
   'higherEducationInstitutions': None,
   'televisionChannels': None},
  'latitude': -75.23502646,
  'longitude': 0.746816168},
 {'id': 30,
  'name': 'Aeropuerto Guillermo León Valencia',
  'iataCode': 'PPN',
  'oaciCode': 'SKPP',
  'type': 'Nacional',
  'deparmentId': 11,
  'department': {'id': 11,
   'name': 'Cauca',
   'description': 'Cauca es uno de los treinta y dos departamentos que, junto al Distrito Capital de Bogotá, conforman la República de Colombia. Su capital y ciudad más poblada es Popayán. Está ubicado al suroccidente del país entre las regiones andina y pacífica, limitando al norte con Valle del Cauca y Tolima, al oriente con Huila, al suroriente con Caquetá, al sur con Putumayo y Nariño, y al noroccidente con el océano Pacífico',
   'cityCapitalId': 399,
   'municipalities': 41,
   'surface': 29308,
   'population': 1516018,
   'phonePrefix': '2',
   'countryId': 1,
   'cityCapital': None,
   'country': None,
   'cities': None,
   'regionId': 2,
   'region': None,
   'naturalAreas': None,
   'maps': None,
   'indigenousReservations': None,
   'airports': [None]},
  'cityId': 399,
  'city': {'id': 399,
   'name': 'Popayán',
   'description': 'Popayán, oficialmente Asunción de Popayán es un municipio colombiano, capital del departamento del Cauca. Se encuentra localizado en el Valle de Pubenza, entre la Cordillera Occidental y Central al suroccidente del país. Su extensión territorial es de 512 km², su altitud media es de 1760 m sobre el nivel del mar, su precipitación media anual de 1941 mm, su temperatura promedio de 14/19\xa0°C y distancia aproximada de 600 km a Bogotá, capital de Colombia.',
   'surface': 512,
   'population': 318059,
   'postalCode': '190001',
   'departmentId': 11,
   'department': None,
   'touristAttractions': None,
   'presidents': None,
   'indigenousReservations': None,
   'airports': [None],
   'radios': None,
   'urbanCenters': None,
   'higherEducationInstitutions': None,

In [24]:
repusesta_json = respuesta_api.json()

In [ ]:
## IMPORTO LA LIBRERIA PANDAS PARA CREAR UN DATAFRAME Y ASI PODER TENER UNA MEJOR VISUALIZACION DE LOS DATOS ##

In [25]:
import pandas as pd

df_api = pd.DataFrame.from_dict(repusesta_json)

In [26]:
df_api

,id,name,iataCode,oaciCode,type,deparmentId,department,cityId,city,latitude,longitude
0,45,Base Aérea BG. Arturo Lema Posada,N/A,N/A,Militar,2,"{'id': 2, 'name': 'Antioquia', 'description': ...",91,"{'id': 91, 'name': 'Rionegro', 'description': ...",-75.420378,6.166336
1,9,Aeropuerto Internacional José María Córdova,MDE,SKRG,Internacional,2,"{'id': 2, 'name': 'Antioquia', 'description': ...",91,"{'id': 91, 'name': 'Rionegro', 'description': ...",-75.423110,6.164533
2,35,Aeropuerto Los Colonizadores,RVE,SKSA,Nacional,3,"{'id': 3, 'name': 'Arauca', 'description': 'Ar...",141,"{'id': 141, 'name': 'Saravena', 'description':...",-71.860560,6.956640
3,41,Aeropuerto Gabriel Vargas Santos,TME,SKTM,Nacional,3,"{'id': 3, 'name': 'Arauca', 'description': 'Ar...",142,"{'id': 142, 'name': 'Tame', 'description': '',...",-71.760299,6.449932
4,16,Aeropuerto Santiago Pérez Quiroz,AUC,SKUC,Nacional,3,"{'id': 3, 'name': 'Arauca', 'description': 'Ar...",143,"{'id': 143, 'name': 'Arauca', 'description': '...",-70.736936,7.068911
5,2,Aeropuerto Internacional Ernesto Cortissoz,BAQ,SKBQ,Internacional,4,"{'id': 4, 'name': 'Atlántico', 'description': ...",144,"{'id': 144, 'name': 'Barranquilla', 'descripti...",-74.780677,10.889461
6,7,Aeropuerto Internacional Rafael Núñez,CTG,SKCG,Internacional,6,"{'id': 6, 'name': 'Bolívar', 'description': 'B...",203,"{'id': 203, 'name': 'El Carmen de Bolívar', 'd...",-75.515334,10.444942
7,43,Aeropuerto del Café,N/A,N/A,En Construccion,8,"{'id': 8, 'name': 'Caldas', 'description': 'Ca...",337,"{'id': 337, 'name': 'Manizales', 'description'...",0.000000,0.000000
8,24,Aeropuerto La Nubia,MZL,SKMZ,Nacional,8,"{'id': 8, 'name': 'Caldas', 'description': 'Ca...",337,"{'id': 337, 'name': 'Manizales', 'description'...",-75.469210,5.029363
9,51,Base Aérea de Tres Esquinas,TQS,SKTQ,Militar,9,"{'id': 9, 'name': 'Caquetá', 'description': 'C...",371,"{'id': 371, 'name': 'Solano', 'description': '...",-75.235026,0.746816
10,30,Aeropuerto Guillermo León Valencia,PPN,SKPP,Nacional,11,"{'id': 11, 'name': 'Cauca', 'description': 'Ca...",399,"{'id': 399, 'name': 'Popayán', 'description': ...",-76.609006,2.454550
11,33,Aeropuerto El Caraño,UIB,SKUI,Nacional,13,"{'id': 13, 'name': 'Chocó', 'description': 'Ch...",467,"{'id': 467, 'name': 'Quibdó', 'description': '...",-76.643402,5.692715
12,47,Base Aérea de Madrid,N/A,SKMA,Militar,15,"{'id': 15, 'name': 'Cundinamarca', 'descriptio...",571,"{'id': 571, 'name': 'Madrid', 'description': '...",-74.270886,4.728474
13,50,Base Aérea Germán Olano (Palanquero),PAL,SKPQ,Militar,15,"{'id': 15, 'name': 'Cundinamarca', 'descriptio...",586,"{'id': 586, 'name': 'Puerto Salgar', 'descript...",-74.656654,5.465754
14,34,Aeropuerto Jorge Enrique González,SJE,SKSJ,Nacional,17,"{'id': 17, 'name': 'Guaviare', 'description': ...",654,"{'id': 654, 'name': 'San José del Guaviare', '...",-72.638840,2.572822
15,27,Aeropuerto Benito Salas,NVA,SKNV,Nacional,18,"{'id': 18, 'name': 'Huila', 'description': 'Hu...",657,"{'id': 657, 'name': 'Neiva', 'description': 'N...",-75.292952,2.947570
16,29,Aeropuerto Contador,PTX,SKPI,Nacional,18,"{'id': 18, 'name': 'Huila', 'description': 'Hu...",681,"{'id': 681, 'name': 'Pitalito', 'description':...",-76.090333,1.857339
17,8,Aeropuerto Internacional Alfredo Vásquez Cobo,LET,SKLT,Internacional,1,"{'id': 1, 'name': 'Amazonas', 'description': '...",1,"{'id': 1, 'name': 'Leticia', 'description': 'L...",-69.942465,-4.192509
18,15,Aeropuerto Antonio Roldán Betancourt,APO,SKLC,Nacional,2,"{'id': 2, 'name': 'Antioquia', 'description': ...",41,"{'id': 41, 'name': 'Carepa', 'description': ''...",-76.715769,7.811817
19,23,Aeropuerto San Luis,IPI,SKIP,Nacional,22,"{'id': 22, 'name': 'Nariño', 'description': 'N...",791,"{'id': 791, 'name': 'Ipiales', 'description': ...",-77.671877,0.861964
20,28,Aeropuerto Antonio Nariño,PSO,SKPS,Nacional,22,"{'id': 22, 'name': 'Nariño', 'description': 'N...",769,"{'id': 769, 'name': 'Pasto', 'description': 'P...",-77.290983,1.396596
21,36,Aeropuerto La Florida,TCO,SKCO,Nacional,22,"{'id': 22, 'name': 'Nariño', 'description': 'N...",828,"{'id': 828, 'name': 'San Andrés de Tumaco', 'd...",-78.751526,1.812502
22,6,Aeropuerto Internacional Camilo Daza,CUC,SKCC,Internacional,23,"{'id': 23, 'name': 'Norte de Santander', 'desc...",870,"{'id': 870, 'name': 'Cúcuta', 'description': '...",-72.514056,7.931400
23,10,Aeropuerto Internacional Matecaña,PEI,SKPE,Internacional,26,"{'id': 26, 'name': 'Risaralda', 'description':...",897,"{'id': 897, 'name': 'Pereira', 'description': ...",-75.739397,4.812697
24,31,Aeropuerto El Embrujo,PVA,SKPV,Nacional,27,"{'id': 27, 'name': 'San Andrés y Providencia',...",911,"{'id': 911, 'name': 'Providencia', 'descriptio...",-81.356268,13.738920
25,11,Aeropuerto Internacional Gustavo Rojas Pinilla,ADZ,SKSP,Internacional,27,"{'id': 27, 'name': 'San Andrés y Providencia',...",912,"{'id': 912, 'name': 'San Andrés', 'description...",-81.750815,12.986377
26,17,Aeropuerto Yariguíes,EJA,SKEJ,Nacional,28,"{'id': 28, 'name': 'Santander', 'description':...",921,"{'id': 921, 'name': 'Barrancabermeja', 'descri...",-73.808123,7.026324
27,18,Aeropuerto Las Brujas,CZU,SKGO,Nacional,29,"{'id': 29, 'name': 'Sucre', 'description': 'Su...",1025,"{'id': 1025, 'name': 'Corozal', 'description':...",-75.283497,9.333006
28,42,Aeropuerto José Celestino Mútis,MQU,SKQU,Nacional,30,"{'id': 30, 'name': 'Tolima', 'description': 'T...",1045,"{'id': 1045, 'name': 'Mariquita', 'description...",-77.392443,6.201854
29,49,Base Aérea de Tolemaida,TOL,SKTI,Militar,30,"{'id': 30, 'name': 'Tolima', 'description': 'T...",1046,"{'id': 1046, 'name': 'Melgar', 'description': ...",-74.693690,4.260574
30,22,Aeropuerto Perales,IBE,SKIB,Nacional,30,"{'id': 30, 'name': 'Tolima', 'description': 'T...",1069,"{'id': 1069, 'name': 'Ibagué', 'description': ...",-75.136257,4.483670
31,40,Aeropuerto Santa Ana,CRC,SKGO,Nacional,31,"{'id': 31, 'name': 'Valle del Cauca', 'descrip...",1079,"{'id': 1079, 'name': 'Cartago', 'description':...",-75.955933,4.758469
32,26,Aeropuerto Fabio Alberto León Bentley,MVP,SKMU,Nacional,32,"{'id': 32, 'name': 'Vaupés', 'description': 'V...",1115,"{'id': 1115, 'name': 'Mitú', 'description': 'M...",-70.233836,1.253549
33,48,Base Aérea de Marandúa,MQZ,SKUA,Militar,33,"{'id': 33, 'name': 'Vichada', 'description': '...",1121,"{'id': 1121, 'name': 'Puerto Carreño', 'descri...",-68.687102,5.525512
34,32,Aeropuerto Germán Olano,PCR,SKPC,Nacional,33,"{'id': 33, 'name': 'Vichada', 'description': '...",1121,"{'id': 1121, 'name': 'Puerto Carreño', 'descri...",-67.521106,6.405930
35,21,Aeropuerto Juan Casiano,GPI,SKGP,Nacional,11,"{'id': 11, 'name': 'Cauca', 'description': 'Ca...",412,"{'id': 412, 'name': 'Guapí', 'description': ''...",-77.894667,2.575232
36,25,Aeropuerto Enrique Olaya Herrera,EOH,SKMD,Nacional,2,"{'id': 2, 'name': 'Antioquia', 'description': ...",12,"{'id': 12, 'name': 'Medellín', 'description': ...",-75.590447,6.220358
37,44,Aeropuerto Militar CATAM,BOG,N/A,Militar,5,"{'id': 5, 'name': 'Bogotá', 'description': 'Bo...",167,"{'id': 167, 'name': 'Bogotá D.C.', 'descriptio...",-74.153035,4.704754
38,19,Aeropuerto Flaminio Suarez Camacho,GYM,SKGY,Nacional,5,"{'id': 5, 'name': 'Bogotá', 'description': 'Bo...",167,"{'id': 167, 'name': 'Bogotá D.C.', 'descriptio...",-74.064630,4.815144
39,3,Aeropuerto Internacional El Dorado,BOG,SKBO,Internacional,5,"{'id': 5, 'name': 'Bogotá', 'description': 'Bo...",167,"{'id': 167, 'name': 'Bogotá D.C.', 'descriptio...",-74.160003,4.698402
40,46,Base Aérea Larandia,N/A,SKLR,Militar,9,"{'id': 9, 'name': 'Caquetá', 'description': 'C...",364,"{'id': 364, 'name': 'Florencia', 'description'...",-75.486502,1.477557
41,20,Aeropuerto Gustavo Artunduaga,FLA,SKFL,Nacional,9,"{'id': 9, 'name': 'Caquetá', 'description': 'C...",364,"{'id': 364, 'name': 'Florencia', 'description'...",-75.560582,1.589564
42,39,Aeropuerto El Alcaraván,EYP,SKYP,Nacional,10,"{'id': 10, 'name': 'Casanare', 'description': ...",380,"{'id': 380, 'name': 'Yopal', 'description': 'Y...",-72.383810,5.317642
43,37,Aeropuerto Alfonso López Pumarejo,VUP,SKVP,Nacional,12,"{'id': 12, 'name': 'Cesar', 'description': 'Ce...",441,"{'id': 441, 'name': 'Valledupar', 'description...",-73.252286,10.433999
44,13,Aeropuerto Internacional Los Garzones,MTR,SKMR,Nacional,14,"{'id': 14, 'name': 'Córdoba', 'description': '...",498,"{'id': 498, 'name': 'Montería', 'description':...",-75.823783,8.826506
45,14,Aeropuerto Internacional Almirante Padilla,RCH,SKRH,Nacional,19,"{'id': 19, 'name': 'La Guajira', 'description'...",694,"{'id': 694, 'name': 'Riohacha', 'description':...",-72.927139,11.523556
46,12,Aeropuerto Internacional Simón Bolívar,SMR,SKSM,Internacional,20,"{'id': 20, 'name': 'Magdalena', 'description':...",709,"{'id': 709, 'name': 'Santa Marta', 'descriptio...",-74.230800,11.119716
47,38,Aeropuerto Vanguardia,VVC,SKVV,Nacional,21,"{'id': 21, 'name': 'Meta', 'description': 'Met...",740,"{'id': 740, 'name': 'Villavicencio', 'descript...",-73.613327,4.169064
48,1,Aeropuerto Internacional El Edén,AXM,SKAR,Internacional,25,"{'id': 25, 'name': 'Quindío', 'description': '...",885,"{'id': 885, 'name': 'Armenia', 'description': ...",-75.765981,4.453243
49,4,Aeropuerto Internacional Palonegro,BGA,SKBG,Internacional,28,"{'id': 28, 'name': 'Santander', 'description':...",915,"{'id': 915, 'name': 'Bucaramanga', 'descriptio...",-73.181348,7.128304
50,52,Base Aérea Marco Fidel Suárez,N/A,SKGB,Militar,31,"{'id': 31, 'name': 'Valle del Cauca', 'descrip...",1093,"{'id': 1093, 'name': 'Cali', 'description': 'C...",-76.495842,3.459497
51,5,Aeropuerto Internacional Alfonso Bonilla Aragón,CLO,SKCL,Internacional,31,"{'id': 31, 'name': 'Valle del Cauca', 'descrip...",1093,"{'id': 1093, 'name': 'Cali', 'description': 'C...",-76.381104,3.538400

In [27]:
df_api['department'] = df_api['department'].apply(
    lambda x: x.get('name') if isinstance(x, dict) else x
)

df_api['city'] = df_api['city'].apply(
    lambda x: x.get('name') if isinstance(x, dict) else x
)

In [28]:
df_api

,id,name,iataCode,oaciCode,type,deparmentId,department,cityId,city,latitude,longitude
0,45,Base Aérea BG. Arturo Lema Posada,N/A,N/A,Militar,2,Antioquia,91,Rionegro,-75.420378,6.166336
1,9,Aeropuerto Internacional José María Córdova,MDE,SKRG,Internacional,2,Antioquia,91,Rionegro,-75.423110,6.164533
2,35,Aeropuerto Los Colonizadores,RVE,SKSA,Nacional,3,Arauca,141,Saravena,-71.860560,6.956640
3,41,Aeropuerto Gabriel Vargas Santos,TME,SKTM,Nacional,3,Arauca,142,Tame,-71.760299,6.449932
4,16,Aeropuerto Santiago Pérez Quiroz,AUC,SKUC,Nacional,3,Arauca,143,Arauca,-70.736936,7.068911
5,2,Aeropuerto Internacional Ernesto Cortissoz,BAQ,SKBQ,Internacional,4,Atlántico,144,Barranquilla,-74.780677,10.889461
6,7,Aeropuerto Internacional Rafael Núñez,CTG,SKCG,Internacional,6,Bolívar,203,El Carmen de Bolívar,-75.515334,10.444942
7,43,Aeropuerto del Café,N/A,N/A,En Construccion,8,Caldas,337,Manizales,0.000000,0.000000
8,24,Aeropuerto La Nubia,MZL,SKMZ,Nacional,8,Caldas,337,Manizales,-75.469210,5.029363
9,51,Base Aérea de Tres Esquinas,TQS,SKTQ,Militar,9,Caquetá,371,Solano,-75.235026,0.746816
10,30,Aeropuerto Guillermo León Valencia,PPN,SKPP,Nacional,11,Cauca,399,Popayán,-76.609006,2.454550
11,33,Aeropuerto El Caraño,UIB,SKUI,Nacional,13,Chocó,467,Quibdó,-76.643402,5.692715
12,47,Base Aérea de Madrid,N/A,SKMA,Militar,15,Cundinamarca,571,Madrid,-74.270886,4.728474
13,50,Base Aérea Germán Olano (Palanquero),PAL,SKPQ,Militar,15,Cundinamarca,586,Puerto Salgar,-74.656654,5.465754
14,34,Aeropuerto Jorge Enrique González,SJE,SKSJ,Nacional,17,Guaviare,654,San José del Guaviare,-72.638840,2.572822
15,27,Aeropuerto Benito Salas,NVA,SKNV,Nacional,18,Huila,657,Neiva,-75.292952,2.947570
16,29,Aeropuerto Contador,PTX,SKPI,Nacional,18,Huila,681,Pitalito,-76.090333,1.857339
17,8,Aeropuerto Internacional Alfredo Vásquez Cobo,LET,SKLT,Internacional,1,Amazonas,1,Leticia,-69.942465,-4.192509
18,15,Aeropuerto Antonio Roldán Betancourt,APO,SKLC,Nacional,2,Antioquia,41,Carepa,-76.715769,7.811817
19,23,Aeropuerto San Luis,IPI,SKIP,Nacional,22,Nariño,791,Ipiales,-77.671877,0.861964
20,28,Aeropuerto Antonio Nariño,PSO,SKPS,Nacional,22,Nariño,769,Pasto,-77.290983,1.396596
21,36,Aeropuerto La Florida,TCO,SKCO,Nacional,22,Nariño,828,San Andrés de Tumaco,-78.751526,1.812502
22,6,Aeropuerto Internacional Camilo Daza,CUC,SKCC,Internacional,23,Norte de Santander,870,Cúcuta,-72.514056,7.931400
23,10,Aeropuerto Internacional Matecaña,PEI,SKPE,Internacional,26,Risaralda,897,Pereira,-75.739397,4.812697
24,31,Aeropuerto El Embrujo,PVA,SKPV,Nacional,27,San Andrés y Providencia,911,Providencia,-81.356268,13.738920
25,11,Aeropuerto Internacional Gustavo Rojas Pinilla,ADZ,SKSP,Internacional,27,San Andrés y Providencia,912,San Andrés,-81.750815,12.986377
26,17,Aeropuerto Yariguíes,EJA,SKEJ,Nacional,28,Santander,921,Barrancabermeja,-73.808123,7.026324
27,18,Aeropuerto Las Brujas,CZU,SKGO,Nacional,29,Sucre,1025,Corozal,-75.283497,9.333006
28,42,Aeropuerto José Celestino Mútis,MQU,SKQU,Nacional,30,Tolima,1045,Mariquita,-77.392443,6.201854
29,49,Base Aérea de Tolemaida,TOL,SKTI,Militar,30,Tolima,1046,Melgar,-74.693690,4.260574
30,22,Aeropuerto Perales,IBE,SKIB,Nacional,30,Tolima,1069,Ibagué,-75.136257,4.483670
31,40,Aeropuerto Santa Ana,CRC,SKGO,Nacional,31,Valle del Cauca,1079,Cartago,-75.955933,4.758469
32,26,Aeropuerto Fabio Alberto León Bentley,MVP,SKMU,Nacional,32,Vaupés,1115,Mitú,-70.233836,1.253549
33,48,Base Aérea de Marandúa,MQZ,SKUA,Militar,33,Vichada,1121,Puerto Carreño,-68.687102,5.525512
34,32,Aeropuerto Germán Olano,PCR,SKPC,Nacional,33,Vichada,1121,Puerto Carreño,-67.521106,6.405930
35,21,Aeropuerto Juan Casiano,GPI,SKGP,Nacional,11,Cauca,412,Guapí,-77.894667,2.575232
36,25,Aeropuerto Enrique Olaya Herrera,EOH,SKMD,Nacional,2,Antioquia,12,Medellín,-75.590447,6.220358
37,44,Aeropuerto Militar CATAM,BOG,N/A,Militar,5,Bogotá,167,Bogotá D.C.,-74.153035,4.704754
38,19,Aeropuerto Flaminio Suarez Camacho,GYM,SKGY,Nacional,5,Bogotá,167,Bogotá D.C.,-74.064630,4.815144
39,3,Aeropuerto Internacional El Dorado,BOG,SKBO,Internacional,5,Bogotá,167,Bogotá D.C.,-74.160003,4.698402
40,46,Base Aérea Larandia,N/A,SKLR,Militar,9,Caquetá,364,Florencia,-75.486502,1.477557
41,20,Aeropuerto Gustavo Artunduaga,FLA,SKFL,Nacional,9,Caquetá,364,Florencia,-75.560582,1.589564
42,39,Aeropuerto El Alcaraván,EYP,SKYP,Nacional,10,Casanare,380,Yopal,-72.383810,5.317642
43,37,Aeropuerto Alfonso López Pumarejo,VUP,SKVP,Nacional,12,Cesar,441,Valledupar,-73.252286,10.433999
44,13,Aeropuerto Internacional Los Garzones,MTR,SKMR,Nacional,14,Córdoba,498,Montería,-75.823783,8.826506
45,14,Aeropuerto Internacional Almirante Padilla,RCH,SKRH,Nacional,19,La Guajira,694,Riohacha,-72.927139,11.523556
46,12,Aeropuerto Internacional Simón Bolívar,SMR,SKSM,Internacional,20,Magdalena,709,Santa Marta,-74.230800,11.119716
47,38,Aeropuerto Vanguardia,VVC,SKVV,Nacional,21,Meta,740,Villavicencio,-73.613327,4.169064
48,1,Aeropuerto Internacional El Edén,AXM,SKAR,Internacional,25,Quindío,885,Armenia,-75.765981,4.453243
49,4,Aeropuerto Internacional Palonegro,BGA,SKBG,Internacional,28,Santander,915,Bucaramanga,-73.181348,7.128304
50,52,Base Aérea Marco Fidel Suárez,N/A,SKGB,Militar,31,Valle del Cauca,1093,Cali,-76.495842,3.459497
51,5,Aeropuerto Internacional Alfonso Bonilla Aragón,CLO,SKCL,Internacional,31,Valle del Cauca,1093,Cali,-76.381104,3.538400

In [30]:
df_api.to_csv(
    r"C:\Users\anfre\Downloads\Aeropuertos_Colombia.csv", 
    index=False
    )